RMD Render Summary (Batch 3/4)
======================================

[SUCCESS] - ./FigureYa251NPHSurv/FigureYa251NPHSurv.Rmd
[FAILED] - ./FigureYa252mclust/FigureYa252mclust.Rmd
--- Error Log for ./FigureYa252mclust/FigureYa252mclust.Rmd ---
/usr/bin/tar: GSE121236_RAW.tar: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
/usr/bin/tar: GSE121236_RAW.tar: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
Error in `open.connection()`:
! cannot open the connection
Backtrace:
    ▆
 1. ├─... %>% do.call(what = cbind)
 2. ├─base::do.call(., what = cbind)
 3. ├─base::lapply(...)
 4. │ └─global FUN(X[[i]], ...)
 5. │   ├─... %$% ...
 6. │   └─utils::read.table(...)
 7. │     ├─base::open(file, "rt")
 8. │     └─base::open.connection(file, "rt")
 9. └─base::with(...)

Quitting from FigureYa252mclust.Rmd:72-94 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa253panGSEA/FigureYa253panGSEA.Rmd
--- Error Log for ./FigureYa253panGSEA/FigureYa253panGSEA.Rmd ---
Error in `fread()`:
! File 'EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv' does not exist or is non-readable. getwd()=='/home/runner/work/FigureYa/FigureYa/FigureYa253panGSEA'
Backtrace:
    ▆
 1. └─data.table::fread(...)
 2.   └─data.table:::stopf(...)
 3.     └─data.table:::raise_condition(...)

Quitting from FigureYa253panGSEA.Rmd:91-108 [unnamed-chunk-3]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa254scViolin/FigureYa254scViolin.Rmd
--- Error Log for ./FigureYa254scViolin/FigureYa254scViolin.Rmd ---
Error in `readChar()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─base::load("sc.seurat.Rdata")
 2.   └─base::readChar(con, 5L, useBytes = TRUE)

Quitting from FigureYa254scViolin.Rmd:96-110 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa255TIME/FigureYa255TIME.Rmd
--- Error Log for ./FigureYa255TIME/FigureYa255TIME.Rmd ---
Error in `library()`:
! there is no package called 'estimate'
Backtrace:
    ▆
 1. └─base::library(estimate)

Quitting from FigureYa255TIME.Rmd:66-81 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa256panelLink/FigureYa256panelLink.Rmd
--- Error Log for ./FigureYa256panelLink/FigureYa256panelLink.Rmd ---
Error in `library()`:
! there is no package called 'crosslink'
Backtrace:
    ▆
 1. └─base::library(crosslink)

Quitting from FigureYa256panelLink.Rmd:40-50 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa257armCNV/FigureYa257armCNV.Rmd
--- Error Log for ./FigureYa257armCNV/FigureYa257armCNV.Rmd ---
Error in `melt.default()`:
! The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is superseded and is no longer actively developed, and this redirection is now deprecated. To continue using melt methods from reshape2 while both packages are attached, e.g. melt.list, you can prepend the namespace, i.e. reshape2::melt(wide). In the next version, this warning will become an error.
Backtrace:
    ▆
 1. ├─base::as.data.frame(melt(wide, measure.vars = c("loss.C1", "loss.C2")))
 2. ├─data.table::melt(wide, measure.vars = c("loss.C1", "loss.C2"))
 3. └─data.table:::melt.default(wide, measure.vars = c("loss.C1", "loss.C2"))
 4.   └─data.table:::stopf(...)
 5.     └─data.table:::raise_condition(...)

Quitting from FigureYa257armCNV.Rmd:166-198 [unnamed-chunk-4]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa258SNF/FigureYa258SNF.Rmd
--- Error Log for ./FigureYa258SNF/FigureYa258SNF.Rmd ---
Error in `loadNamespace()`:
! there is no package called 'wateRmelon'
Backtrace:
    ▆
 1. ├─base::as.data.frame(wateRmelon::Beta2M(beta))
 2. └─base::loadNamespace(x)
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)

Quitting from FigureYa258SNF.Rmd:101-129 [unnamed-chunk-3]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa259circLink/FigureYa259circLink.Rmd
--- Error Log for ./FigureYa259circLink/FigureYa259circLink.Rmd ---
Error in `library()`:
! there is no package called 'crosslink'
Backtrace:
    ▆
 1. └─base::library(crosslink)

Quitting from FigureYa259circLink.Rmd:87-100 [unnamed-chunk-2]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa25Sankey_update/FigureYa25Sankey_update.Rmd
[SUCCESS] - ./FigureYa260CNV/FigureYa260CNV.Rmd
[SUCCESS] - ./FigureYa261circGene/FigureYa261circGene.Rmd
[SUCCESS] - ./FigureYa262GDC/FigureYa262GDC.Rmd
[FAILED] - ./FigureYa263panDiff/FigureYa263panDiff.Rmd
--- Error Log for ./FigureYa263panDiff/FigureYa263panDiff.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa263panDiff.Rmd:111-175 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa264epiImmune/FigureYa264epiImmune.Rmd
--- Error Log for ./FigureYa264epiImmune/FigureYa264epiImmune.Rmd ---
Error in `library()`:
! there is no package called 'immunedeconv'
Backtrace:
    ▆
 1. └─base::library(immunedeconv)

Quitting from FigureYa264epiImmune.Rmd:68-92 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa265panCNV/FigureYa265panCNV.Rmd
--- Error Log for ./FigureYa265panCNV/FigureYa265panCNV.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa265panCNV.Rmd:116-166 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa266panHeatmap/FigureYa266panHeatmap.Rmd
--- Error Log for ./FigureYa266panHeatmap/FigureYa266panHeatmap.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa266panHeatmap.Rmd:112-185 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa267scCellChat/FigureYa267scCellChat.Rmd
--- Error Log for ./FigureYa267scCellChat/FigureYa267scCellChat.Rmd ---
Warning: invalid package ‘ifnb.SeuratData_3.1.0.tar.gz’
Error: ERROR: no packages specified
Error in `library()`:
! there is no package called 'SeuratData'
Backtrace:
    ▆
 1. └─base::library(SeuratData)

Quitting from FigureYa267scCellChat.Rmd:80-103 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa268panCNVexpr/FigureYa268panCNVexpr.Rmd
--- Error Log for ./FigureYa268panCNVexpr/FigureYa268panCNVexpr.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa268panCNVexpr.Rmd:119-240 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa269scMetabolism/FigureYa269scMetabolism.Rmd
--- Error Log for ./FigureYa269scMetabolism/FigureYa269scMetabolism.Rmd ---
Error in `library()`:
! there is no package called 'SeuratData'
Backtrace:
    ▆
 1. └─base::library(SeuratData)

Quitting from FigureYa269scMetabolism.Rmd:36-52 [unnamed-chunk-1]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa26circos_R/FigureYa26circos_R.Rmd
[FAILED] - ./FigureYa270panMeth/FigureYa270panMeth.Rmd
--- Error Log for ./FigureYa270panMeth/FigureYa270panMeth.Rmd ---
trying URL 'https://bioconductor.org//packages/3.21/bioc/src/contrib/ChAMP_2.38.0.tar.gz'
Content type 'application/x-gzip' length 8337757 bytes (8.0 MB)
==================================================
downloaded 8.0 MB

ERROR: dependency ‘kpmt’ is not available for package ‘ChAMP’
Perhaps try a variation of:
install.packages('kpmt')
* removing ‘/home/runner/work/_temp/Library/ChAMP’

The downloaded source packages are in
	'/tmp/RtmpP0Yw4q/downloaded_packages'
Error in `library()`:
! there is no package called 'ChAMP'
Backtrace:
    ▆
 1. └─base::library(ChAMP)

Quitting from FigureYa270panMeth.Rmd:70-120 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa271panMethExpr/FigureYa271panMethExpr.Rmd
--- Error Log for ./FigureYa271panMethExpr/FigureYa271panMethExpr.Rmd ---
trying URL 'https://bioconductor.org//packages/3.21/bioc/src/contrib/ChAMP_2.38.0.tar.gz'
Content type 'application/x-gzip' length 8337757 bytes (8.0 MB)
==================================================
downloaded 8.0 MB

ERROR: dependency ‘kpmt’ is not available for package ‘ChAMP’
Perhaps try a variation of:
install.packages('kpmt')
* removing ‘/home/runner/work/_temp/Library/ChAMP’

The downloaded source packages are in
	'/tmp/RtmpGHtvBF/downloaded_packages'
Error in `library()`:
! there is no package called 'ChAMP'
Backtrace:
    ▆
 1. └─base::library(ChAMP)

Quitting from FigureYa271panMethExpr.Rmd:67-90 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa272scBulkCCCI/FigureYa272scBulkCCCI.Rmd
--- Error Log for ./FigureYa272scBulkCCCI/FigureYa272scBulkCCCI.Rmd ---
Warning: invalid package ‘ScBulkCCCI_0.1.3.tar.gz’
Error: ERROR: no packages specified
Error in `library()`:
! there is no package called 'ScBulkCCCI'
Backtrace:
    ▆
 1. └─base::library("ScBulkCCCI")

Quitting from FigureYa272scBulkCCCI.Rmd:101-120 [unnamed-chunk-3]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa273BAPC/FigureYa273BAPC.Rmd
[FAILED] - ./FigureYa274MuSiCbulkProop/FigureYa274MuSiCbulkProop.Rmd
--- Error Log for ./FigureYa274MuSiCbulkProop/FigureYa274MuSiCbulkProop.Rmd ---
Error in `library()`:
! there is no package called 'SeuratData'
Backtrace:
    ▆
 1. └─base::library(SeuratData)

Quitting from FigureYa274MuSiCbulkProop.Rmd:78-99 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa275scAUCell/FigureYa275scAUCell.Rmd
--- Error Log for ./FigureYa275scAUCell/FigureYa275scAUCell.Rmd ---
Error in `library()`:
! there is no package called 'SeuratData'
Backtrace:
    ▆
 1. └─base::library(SeuratData)

Quitting from FigureYa275scAUCell.Rmd:69-90 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa276panSNV/FigureYa276panSNV.Rmd
--- Error Log for ./FigureYa276panSNV/FigureYa276panSNV.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa276panSNV.Rmd:89-112 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa277Immunomodulator/FigureYa277Immunomodulator.Rmd
--- Error Log for ./FigureYa277Immunomodulator/FigureYa277Immunomodulator.Rmd ---
Error in `library()`:
! there is no package called 'genefu'
Backtrace:
    ▆
 1. └─base::library(genefu)

Quitting from FigureYa277Immunomodulator.Rmd:84-117 [unnamed-chunk-3]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa278heatmapPoints/FigureYa278heatmapPoints.Rmd
[FAILED] - ./FigureYa279panGeneGSEA/FigureYa279panGeneGSEA.Rmd
--- Error Log for ./FigureYa279panGeneGSEA/FigureYa279panGeneGSEA.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa279panGeneGSEA.Rmd:83-157 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa27tSNE_update/FIgureYa27tSNE_update.Rmd
--- Error Log for ./FigureYa27tSNE_update/FIgureYa27tSNE_update.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim("./tung/molecules.txt", header = TRUE, row.names = 1)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FIgureYa27tSNE_update.Rmd:119-126 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa280TMEofSTS/FigureYa280TMEofSTS.Rmd
--- Error Log for ./FigureYa280TMEofSTS/FigureYa280TMEofSTS.Rmd ---
trying URL 'https://github.com/ebecht/MCPcounter/raw/master/Source/MCPcounter_1.2.0.tar.gz'
Error in `library()`:
! there is no package called 'MCPcounter'
Backtrace:
    ▆
 1. └─base::library(MCPcounter)

Quitting from FigureYa280TMEofSTS.Rmd:54-82 [unnamed-chunk-1]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa281wheel/FigureYa281wheel.Rmd
[SUCCESS] - ./FigureYa282CMAP_XSum/FigureYa282CMAP_XSum.Rmd
[SUCCESS] - ./FigureYa283vennyPvalue/FigureYa283vennyPvalue.Rmd
[SUCCESS] - ./FigureYa284pairwiseLogrank/FigureYa284pairwiseLogrank.Rmd
[FAILED] - ./FigureYa285scRNA_monocle/FigureYa285scRNA_monocle.Rmd
--- Error Log for ./FigureYa285scRNA_monocle/FigureYa285scRNA_monocle.Rmd ---
Error in `source()`:
! install_dependencies.R:39:14: unexpected 'function'
38:       cat("Successfully installed:", package_name, "\n")
39:     }, error function
                 ^
Backtrace:
    ▆
 1. └─base::source("install_dependencies.R")

Quitting from FigureYa285scRNA_monocle.Rmd:46-64 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa286ExprCorORR/FigureYa286ExprCorORR.Rmd
--- Error Log for ./FigureYa286ExprCorORR/FigureYa286ExprCorORR.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa286ExprCorORR.Rmd:97-203 [unnamed-chunk-3]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa287L2logV2/FigureYa287L2log.Rmd
[SUCCESS] - ./FigureYa288MutualExclusivity/FigureYa288MutualExclusivity.Rmd
[FAILED] - ./FigureYa289TILSig/FigureYa289TILSig.Rmd
--- Error Log for ./FigureYa289TILSig/FigureYa289TILSig.Rmd ---

* installing *source* package ‘DealGPL570’ ...
** this is package ‘DealGPL570’ version ‘0.0.1’
** package ‘DealGPL570’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘gunzip’ is not exported by 'namespace:GEOquery'
Execution halted
ERROR: lazy loading failed for package ‘DealGPL570’
* removing ‘/home/runner/work/_temp/Library/DealGPL570’
Error in `library()`:
! there is no package called 'DealGPL570'
Backtrace:
    ▆
 1. └─base::library(DealGPL570)

Quitting from FigureYa289TILSig.Rmd:48-81 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa28color/FigureYa28color.Rmd
--- Error Log for ./FigureYa28color/FigureYa28color.Rmd ---
Error in `library()`:
! there is no package called 'rPlotter'
Backtrace:
    ▆
 1. └─base::library(rPlotter)

Quitting from FigureYa28color.Rmd:62-69 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa290BarGraph/FigureYa290BarGraph.Rmd
--- Error Log for ./FigureYa290BarGraph/FigureYa290BarGraph.Rmd ---
Error in `library()`:
! there is no package called 'SeuratDisk'
Backtrace:
    ▆
 1. └─base::library(SeuratDisk)

Quitting from FigureYa290BarGraph.Rmd:50-66 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa291PancanProgSigatureV2/FigureYa291PancanProgSigatureV2.Rmd
--- Error Log for ./FigureYa291PancanProgSigatureV2/FigureYa291PancanProgSigatureV2.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa291PancanProgSigatureV2.Rmd:105-155 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa292HCCsubtype/FigureYa292HCCsubtype.Rmd
--- Error Log for ./FigureYa292HCCsubtype/FigureYa292HCCsubtype.Rmd ---
Error in `library()`:
! there is no package called 'CMScaller'
Backtrace:
    ▆
 1. └─base::library(CMScaller)

Quitting from FigureYa292HCCsubtype.Rmd:74-95 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa293machineLearning/FigureYa293machineLearning.Rmd
--- Error Log for ./FigureYa293machineLearning/FigureYa293machineLearning.Rmd ---
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (plsRcox)

The downloaded source packages are in
	'/tmp/Rtmp2sSsJD/downloaded_packages'
Error in `library()`:
! there is no package called 'CoxBoost'
Backtrace:
    ▆
 1. └─base::library(CoxBoost)

Quitting from FigureYa293machineLearning.Rmd:85-113 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa294HCCdrug/FigureYa294HCCdrug.Rmd
--- Error Log for ./FigureYa294HCCdrug/FigureYa294HCCdrug.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.csv(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa294HCCdrug.Rmd:190-266 [unnamed-chunk-5]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa295ClassDiscovery/FigureYa295ClassDiscovery.Rmd
--- Error Log for ./FigureYa295ClassDiscovery/FigureYa295ClassDiscovery.Rmd ---
Error in `shell()`:
! could not find function "shell"
Backtrace:
    ▆
 1. └─classpredict::classPredict(...)

Quitting from FigureYa295ClassDiscovery.Rmd:118-384 [unnamed-chunk-3]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa296VIPER/FigureYa296VIPER.Rmd
--- Error Log for ./FigureYa296VIPER/FigureYa296VIPER.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.table(...)
 2.   └─base::file(file, "rt")

Quitting from FigureYa296VIPER.Rmd:107-155 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa297Rbar/FigureYa297Rbar.Rmd
--- Error Log for ./FigureYa297Rbar/FigureYa297Rbar.Rmd ---
* removing ‘/home/runner/work/_temp/Library/gridpattern’
ERROR: dependency ‘transformr’ is not available for package ‘gganimate’
Perhaps try a variation of:
install.packages('transformr')
* removing ‘/home/runner/work/_temp/Library/gganimate’
ERROR: dependency ‘gridpattern’ is not available for package ‘ggpattern’
Perhaps try a variation of:
install.packages('gridpattern')
* removing ‘/home/runner/work/_temp/Library/ggpattern’

The downloaded source packages are in
	'/tmp/Rtmpb5NCWI/downloaded_packages'
Error in `library()`:
! there is no package called 'ggpattern'
Backtrace:
    ▆
 1. └─base::library(ggpattern)

Quitting from FigureYa297Rbar.Rmd:63-81 [unnamed-chunk-1]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa298ecdfPvalue/FigureYa298ecdfPvalue.Rmd
[FAILED] - ./FigureYa299pancanSurv/FigureYa299pancanSurv.Rmd
--- Error Log for ./FigureYa299pancanSurv/FigureYa299pancanSurv.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa299pancanSurv.Rmd:91-151 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa2ggtree+pheatmap+msa/FigureYa2ggtree+pheatmap+msa.Rmd
--- Error Log for ./FigureYa2ggtree+pheatmap+msa/FigureYa2ggtree+pheatmap+msa.Rmd ---
Error in `readAAStringSet()`:
! could not find function "readAAStringSet"

Quitting from FigureYa2ggtree+pheatmap+msa.Rmd:83-108 [unnamed-chunk-2]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa300pancanCor/FigureYa300pancanCor.Rmd
--- Error Log for ./FigureYa300pancanCor/FigureYa300pancanCor.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.delim(...)
 2.   └─utils::read.table(...)
 3.     └─base::file(file, "rt")

Quitting from FigureYa300pancanCor.Rmd:142-190 [unnamed-chunk-3]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa301scCoExpr/FigureYa301scCoExpr.Rmd
--- Error Log for ./FigureYa301scCoExpr/FigureYa301scCoExpr.Rmd ---
Error in `library()`:
! there is no package called 'SeuratData'
Backtrace:
    ▆
 1. └─base::library(SeuratData)

Quitting from FigureYa301scCoExpr.Rmd:70-87 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa302NTPPAM/FigureYa302NTPPAM.Rmd
--- Error Log for ./FigureYa302NTPPAM/FigureYa302NTPPAM.Rmd ---
Error in `library()`:
! there is no package called 'CMScaller'
Backtrace:
    ▆
 1. └─base::library(CMScaller)

Quitting from FigureYa302NTPPAM.Rmd:78-92 [unnamed-chunk-1]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa303panCircos/FigureYa303panCircos.Rmd
[FAILED] - ./FigureYa304MAGIC/FigureYa304MAGIC.Rmd
--- Error Log for ./FigureYa304MAGIC/FigureYa304MAGIC.Rmd ---
Requirement already satisfied: kiwisolver>=1.3.1 in /home/runner/.virtualenvs/r-reticulate/lib/python3.11/site-packages (from matplotlib->magic-impute) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/runner/.virtualenvs/r-reticulate/lib/python3.11/site-packages (from matplotlib->magic-impute) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/runner/.virtualenvs/r-reticulate/lib/python3.11/site-packages (from matplotlib->magic-impute) (3.2.4)
Using cached pandas-2.0.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.2
    Uninstalling pandas-2.3.2:
      Successfully uninstalled pandas-2.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anndata 0.12.2 requires pandas!=2.1.2,>=2.1.0, but you have pandas 2.0.3 which is incompatible.
Successfully installed pandas-2.0.3
Error in `library()`:
! there is no package called 'SeuratDisk'
Backtrace:
    ▆
 1. └─base::library(SeuratDisk)

Quitting from FigureYa304MAGIC.Rmd:43-54 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa304MAGIC/FigureYa304MAGIC_lowMemory.Rmd
--- Error Log for ./FigureYa304MAGIC/FigureYa304MAGIC_lowMemory.Rmd ---
  4.       ├─xfun:::handle_error(...)
  5.       ├─base::withCallingHandlers(...)
  6.       └─knitr:::process_group(group)
  7.         └─knitr:::call_block(x)
  8.           └─knitr:::block_exec(params)
  9.             ├─knitr:::in_input_dir(engine(options))
 10.             │ └─knitr:::in_dir(input_dir(), expr)
 11.             └─knitr (local) engine(options)
Warning message:
In system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) :
  running command ''bash'  -c 'git clone https://github.com/KrishnaswamyLab/MAGIC
cd MAGIC/python
python setup.py install --user
cd ../Rmagic
R CMD INSTALL .

pip install python-libmagic' 2>&1' had status 1

Quitting from FigureYa304MAGIC_lowMemory.Rmd:32-40 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa305PMAPscore/FigureYa305PMAPscore.Rmd
--- Error Log for ./FigureYa305PMAPscore/FigureYa305PMAPscore.Rmd ---
Error in `library()`:
! there is no package called 'PMAPscore'
Backtrace:
    ▆
 1. └─base::library(PMAPscore)

Quitting from FigureYa305PMAPscore.Rmd:58-79 [unnamed-chunk-1]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa306slingshot/FigureYa306slingshot.Rmd
[SUCCESS] - ./FigureYa307CNVHeatmap/FigureYa307CNVHeatmap.Rmd
[FAILED] - ./FigureYa308IHS/FigureYa308IHS.Rmd
--- Error Log for ./FigureYa308IHS/FigureYa308IHS.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.table("Renji_cohort_MR_exp.matrix", header = T, row.names = 1)
 2.   └─base::file(file, "rt")

Quitting from FigureYa308IHS.Rmd:151-186 [unnamed-chunk-3]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa30nomogram_update/FigureYa30nomogram_update.Rmd
[FAILED] - ./FigureYa310CPDBChordGramV2/FigureYa310CPDBChordGramV2.Rmd
--- Error Log for ./FigureYa310CPDBChordGramV2/FigureYa310CPDBChordGramV2.Rmd ---
Error in `library()`:
! there is no package called 'ktplots'
Backtrace:
    ▆
 1. └─base::library(ktplots)

Quitting from FigureYa310CPDBChordGramV2.Rmd:63-84 [unnamed-chunk-1]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa311PAM50Heatmap/FigureYa311PAM50Heatmap.Rmd
--- Error Log for ./FigureYa311PAM50Heatmap/FigureYa311PAM50Heatmap.Rmd ---
Error in `file()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─utils::read.table(...)
 2.   └─base::file(file, "rt")

Quitting from FigureYa311PAM50Heatmap.Rmd:107-131 [unnamed-chunk-2]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa312CellPreference/FigureYa312CellPreference.Rmd
[SUCCESS] - ./FigureYa313CircularPlot/FigureYa313CircularPlot.Rmd
[FAILED] - ./FigureYa314SingleRScore/FigureYa314SingleRScore.Rmd
--- Error Log for ./FigureYa314SingleRScore/FigureYa314SingleRScore.Rmd ---
Error in `seu.objs[[1]]`:
! subscript out of bounds

Quitting from FigureYa314SingleRScore.Rmd:102-137 [unnamed-chunk-4]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa315SingleRFraction/FigureYa315SingleRFraction.Rmd
--- Error Log for ./FigureYa315SingleRFraction/FigureYa315SingleRFraction.Rmd ---
Error:
! error in evaluating the argument 'x' in selecting a method for function 'merge': subscript out of bounds
Backtrace:
    ▆
 1. ├─base::merge(seu.objs[[1]], seu.objs[-1])
 2. └─base (local) `<fn>`(`<sbscOOBE>`)

Quitting from FigureYa315SingleRFraction.Rmd:100-131 [unnamed-chunk-2]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa316RF_XGBoost_Boruta/FigureYa316RF_XGBoost_Boruta.Rmd
[FAILED] - ./FigureYa317RoeDot/FigureYa317RoeDot.Rmd
--- Error Log for ./FigureYa317RoeDot/FigureYa317RoeDot.Rmd ---
Error in `gzfile()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─base::readRDS("seu.rds")
 2.   └─base::gzfile(file, "rb")

Quitting from FigureYa317RoeDot.Rmd:179-194 [unnamed-chunk-3]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa318GenesetDEDotplot/FigureYa318GenesetDEDotplot.Rmd
--- Error Log for ./FigureYa318GenesetDEDotplot/FigureYa318GenesetDEDotplot.Rmd ---
Error in `gzfile()`:
! cannot open the connection
Backtrace:
    ▆
 1. └─base::readRDS("seu.rds")
 2.   └─base::gzfile(file, "rb")

Quitting from FigureYa318GenesetDEDotplot.Rmd:169-217 [unnamed-chunk-3]
Execution halted
-----------------------------------
[FAILED] - ./FigureYa319ContribScore/FigureYa319ContribScore.Rmd
--- Error Log for ./FigureYa319ContribScore/FigureYa319ContribScore.Rmd ---
Error in `fileOpen()`:
! File InputData/GSE163465_series_matrix.txt.gz does not appear to exist.
Backtrace:
    ▆
 1. └─GEOquery::getGEO(filename = file.path(data.path, "GSE163465_series_matrix.txt.gz"))
 2.   └─GEOquery::parseGEO(...)
 3.     └─GEOquery:::fileOpen(fname)

Quitting from FigureYa319ContribScore.Rmd:76-191 [unnamed-chunk-2]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa31lasso_update/FigureYa31lasso_update.Rmd
[FAILED] - ./FigureYa320ClontypeHeatmap/FigureYa320ClontypeHeatmap.Rmd
--- Error Log for ./FigureYa320ClontypeHeatmap/FigureYa320ClontypeHeatmap.Rmd ---
Error in `colnames<-`:
! attempt to set 'colnames' on an object with less than two dimensions
Backtrace:
    ▆
 1. └─base::`colnames<-`(`*tmp*`, value = `<chr>`)

Quitting from FigureYa320ClontypeHeatmap.Rmd:79-113 [unnamed-chunk-2]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa321volcanoSE/FigureYa321volcanoSE.Rmd
[FAILED] - ./FigureYa322SSEA/FigureYa322SSEA.Rmd
--- Error Log for ./FigureYa322SSEA/FigureYa322SSEA.Rmd ---
Error in `colnames<-`:
! attempt to set 'colnames' on an object with less than two dimensions
Backtrace:
    ▆
 1. ├─base::`colnames<-`(`*tmp*`, value = `<chr>`)
 2. └─base::`colnames<-`(`*tmp*`, value = `<chr>`)

Quitting from FigureYa322SSEA.Rmd:123-162 [unnamed-chunk-3]
Execution halted
-----------------------------------
[SUCCESS] - ./FigureYa323STpathseq/FigureYa323STpathseq.Rmd
